In [1]:
import numpy as np

In [2]:
a = np.zeros(10)

In [3]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a[0] = 20
a

array([20.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

## Creating arrays to hold data


In [9]:
b = np.zeros(50, int)

In [10]:
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [11]:
b = np.ones(40, int)

In [12]:
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
def func(a, b, names):
    bmi = a / (b**2)
    for i in range(len(names)):
        print('The BMI of', names[i], 'is', bmi[i])

In [29]:
height = np.zeros(5)
weight = np.zeros(5)

names = ['Ali', 'Amjad', 'Aliyan', 'Ahmad', 'Abdullah']

for i in range(len(names)):
    h = float(input('Enter height of '+names[i]+': '))
    w = float(input('Enter weight of '+names[i]+': '))

    height[i] = h
    weight[i] = w
    
    

Enter height of Ali:  2
Enter weight of Ali:  56
Enter height of Amjad:  2
Enter weight of Amjad:  45
Enter height of Aliyan:  1
Enter weight of Aliyan:  78
Enter height of Ahmad:  1.5
Enter weight of Ahmad:  65
Enter height of Abdullah:  4.3
Enter weight of Abdullah:  67


In [30]:
func(weight, height, names)

The BMI of Ali is 14.0
The BMI of Amjad is 11.25
The BMI of Aliyan is 78.0
The BMI of Ahmad is 28.88888888888889
The BMI of Abdullah is 3.6235803136830724


## Shuffle random

In [43]:
arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[1 3 2 6 4 5]


In [54]:
arr = np.array([1,2,3,4,5,6])
np.random.choice(arr)

3

In [57]:
# 0 -> 100
current_position = 0
dice = np.array([1,2,3,4,5,6])
while current_position < 100:   
    con = input('Press enter to make your turn: ')
    random = np.random.choice(dice)
    current_position = current_position + random

    print('Current Position -> ', current_position)

Press enter to make your turn:  


Current Position ->  5


Press enter to make your turn:  


Current Position ->  8


Press enter to make your turn:  


Current Position ->  14


Press enter to make your turn:  


Current Position ->  19


Press enter to make your turn:  


Current Position ->  24


Press enter to make your turn:  


Current Position ->  29


Press enter to make your turn:  


Current Position ->  35


Press enter to make your turn:  


Current Position ->  39


Press enter to make your turn:  


Current Position ->  45


Press enter to make your turn:  


Current Position ->  48


Press enter to make your turn:  


Current Position ->  50


Press enter to make your turn:  


Current Position ->  53


Press enter to make your turn:  


Current Position ->  58


Press enter to make your turn:  


Current Position ->  63


Press enter to make your turn:  


Current Position ->  64


Press enter to make your turn:  


Current Position ->  69


Press enter to make your turn:  


Current Position ->  70


Press enter to make your turn:  


Current Position ->  74


Press enter to make your turn:  


Current Position ->  77


Press enter to make your turn:  


Current Position ->  78


Press enter to make your turn:  


Current Position ->  80


Press enter to make your turn:  


Current Position ->  83


Press enter to make your turn:  


Current Position ->  89


Press enter to make your turn:  


Current Position ->  90


Press enter to make your turn:  


Current Position ->  92


Press enter to make your turn:  


Current Position ->  97


Press enter to make your turn:  


Current Position ->  98


Press enter to make your turn:  


Current Position ->  104


## Save and load numpy arrays

In [60]:
bmi = weight / (height**2)

In [61]:
np.save('bmi_data', bmi)

In [62]:
np.load('bmi_data.npy')

array([14.        , 11.25      , 78.        , 28.88888889,  3.62358031])

## Generate alot of numbers

In [64]:
np.arange(1,110)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109])

In [88]:
np.random.randint(4, 8, size = 20)

array([4, 7, 5, 7, 7, 4, 7, 7, 5, 7, 7, 6, 5, 7, 5, 7, 4, 7, 5, 5])

In [91]:
np.full(100, 65)

array([65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65])